set_property SRC_FILE_INFO {cfile:D:/work/VHDL/lab5/lab5_2/lab5_2.srcs/constrs_1/new/lab5_2_debug.xdc rfile:../../../lab5_2.srcs/constrs_1/new/lab5_2_debug.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_gen_mmcm.mmcm_i_0]]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[7]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[8]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[9]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[10]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[11]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[12]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[13]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[14]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[15]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_out[16]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[7]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[8]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[9]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[10]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[11]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[12]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[13]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[14]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[15]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[16]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[17]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[18]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[19]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[20]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[21]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[22]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[23]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[24]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[25]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[26]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[27]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[28]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[29]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[30]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DATAPATH/data_in[31]}]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[7]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr_s[8]}]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[7]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/addr_s[8]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/state[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/state[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/state[2]}]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[7]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[8]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[9]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[10]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[11]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[12]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[13]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[14]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[15]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT/wdata[16]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/state[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/state[1]}]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/next_state[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/next_state[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/next_state[2]}]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/addr[7]}]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/waddr[7]}]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[2]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[3]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[4]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[5]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[6]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[7]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[8]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[9]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[10]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[11]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[12]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[13]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[14]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[15]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[16]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[17]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[18]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[19]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[20]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[21]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[22]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[23]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[24]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[25]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[26]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[27]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[28]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[29]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[30]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN/wdata[31]}]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 13 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/done {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_IN_SYNC/state_dest[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_IN_SYNC/state_dest[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_OUT_SYNC/state_dest[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_OUT_SYNC/state_dest[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_IN_SYNC/state_src[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_IN_SYNC/state_src[1]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_OUT_SYNC/state_src[0]} {design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_OUT_SYNC/state_src[1]} design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_IN_SYNC/ack_s design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_IN_SYNC/send_s design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_OUT_SYNC/send_s design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_DP_OUT_SYNC/ack_s]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/go]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/received]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_IN_ADDR_GEN/send]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list design_1_i/myip2_0/U0/myip2_v1_0_S00_AXI_inst/U_WRAPPER/U_USER_APP/U_MEM_OUT_ADDR_GEN/wen]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_2_clk_out2]
